# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LSM_PGD_Cpp <- function(A, Z, alpha, step_size_z, step_size_alpha, niter, trace = FALSE) {
    .Call(`_randnet_LSM_PGD_Cpp`, A, Z, alpha, step_size_z, step_size_alpha, niter, trace)
}

